"""Generate our own fictional PDF and explicit recipe; no third-party financial content."""

import argparse
import hashlib
import json
from pathlib import Path

from reportlab.pdfgen import canvas


def create_demo(directory: Path) -> tuple[Path, dict, dict]:
    directory.mkdir(parents=True, exist_ok=True)
    pdf_path = directory / "synthetic-results.pdf"
    pdf = canvas.Canvas(str(pdf_path), pagesize=(600, 500), invariant=True)
    pdf.setTitle("Margin synthetic financial results - fictional data")
    pdf.setFont("Helvetica", 12)
    for x, y, text in [
        (40, 465, "SYNTHETIC - NOT FINANCIAL EVIDENCE"),
        (40, 440, "Aarya Software Limited (Fictional)"),
        (40, 415, "Consolidated"),
        (40, 390, "Ind AS"),
        (40, 365, "INR crore"),
        (40, 330, "Quarter: 1 July 2025 to 30 September 2025"),
        (40, 280, "Revenue from operations"),
        (380, 280, "1,234.50"),
        (40, 240, "Profit before tax"),
        (380, 240, "(120.25)"),
        (40, 200, "Profit for the period"),
        (380, 200, "-"),
        (40, 130, "Generated by Margin for parser testing."),
    ]:
        pdf.drawString(x, y, text)
    pdf.save()

    def anchor(text, bbox):
        return {"page": 1, "bbox": bbox, "expected_text": text}

    mappings = []
    for metric, label, top in [
        ("revenue_from_operations", "Revenue from operations", 208),
        ("profit_before_tax", "Profit before tax", 248),
        ("profit_for_period", "Profit for the period", 288),
    ]:
        mappings.append(
            {
                "metric": metric,
                "period_start": "2025-07-01",
                "period_end": "2025-09-30",
                "period_kind": "quarter",
                "reporting_basis": "consolidated",
                "accounting_standard": "Ind AS",
                "currency": "INR",
                "source_scale": "crore",
                "label": anchor(label, [35, top, 300, top + 18]),
                "value": {"page": 1, "bbox": [375, top, 480, top + 18]},
                "period_header": anchor(
                    "Quarter: 1 July 2025 to 30 September 2025", [35, 158, 400, 180]
                ),
                "basis_header": anchor("Consolidated", [35, 73, 200, 95]),
                "unit_header": anchor("INR crore", [35, 123, 200, 145]),
                "standard_header": anchor("Ind AS", [35, 98, 200, 120]),
            }
        )
    manifest = {
        "schema_version": 1,
        "company_id": "demo-aarya-software",
        "issuer_name": "Aarya Software Limited (Fictional)",
        "filing_id": "demo-aarya-fy26-q2-consolidated",
        "title": "Synthetic results",
        "data_kind": "synthetic",
        "published_on": "2025-10-20",
        "acquired_at": "2026-09-23T12:00:00Z",
        "usage_basis": "Margin-generated test fixture",
        "processing_scope": "local_only",
    }
    recipe = {
        "schema_version": 1,
        "document_sha256": hashlib.sha256(pdf_path.read_bytes()).hexdigest(),
        "mappings": mappings,
    }
    for filename, payload in [("document.json", manifest), ("recipe.json", recipe)]:
        (directory / filename).write_text(json.dumps(payload, indent=2) + "\n")
    return pdf_path, manifest, recipe


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    path, _, _ = create_demo(args.output)
    print(path)
